# Created by: Vladimir Vinogradenko <vladimirv@ixsystems.com>
# $FreeBSD$

PORTNAME=		ntpstat
DISTVERSION=	0.0.0
CATEGORIES=		net

MAINTAINER=	themylogin@gmail.com
COMMENT=	Shows network time protocol (ntp) status

LICENSE=	GPLv2

USE_GITHUB=		yes

GH_ACCOUNT=		darkhelmet
GH_PROJECT=		ntpstat
GH_TAGNAME=		86e0a68df62e7f6b6c5ee97ee9d15b5e28a4b359

PLIST_FILES=	bin/ntpstat

.include <bsd.port.mk>
