# $FreeBSD$

PORTNAME=	natural
PORTVERSION=	0.1.5
PORTREVISION=	1
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jpaetzel@FreeBSD.org
COMMENT=	Convert data to their natural (human-readable) format

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	freenas
GH_TAGNAME=	83bf9c8

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}six>0:${PORTSDIR}/devel/py-six

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
