# $FreeBSD$

PORTNAME=	natural
PORTVERSION=	0.1.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@ixsystems.com
COMMENT=	Convert data to their natural (human-readable) format

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
