# $FreeBSD$
#

    COMMENT = FreeNAS specific ports

    SUBDIR += freenas-files
    SUBDIR += freenas-installer
    SUBDIR += freenas-migrate93
    SUBDIR += freenas-pkgtools
    SUBDIR += freenas-ui
    SUBDIR += freenas-webui
    SUBDIR += node9
    SUBDIR += npm5
    SUBDIR += pipewatcher
    SUBDIR += py-bsd
    SUBDIR += py-licenselib
    SUBDIR += py-middlewared
    SUBDIR += swagger-ui

.include <bsd.port.subdir.mk>
