# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD$

PORTNAME=	sysctl
PORTVERSION=	0.2.20190530
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Wrapper for the sysctl system functions

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

USE_GITHUB=	yes
GH_ACCOUNT=	william-gr
GH_PROJECT=	py-sysctl
GH_TAGNAME=	2517537

.include <bsd.port.mk>
