#!/bin/sh

case "$2" in
    PRE-INSTALL)
    if [ ! -d /usr/local/share/glib-2.0/schemas ] ; then
        mkdir -p /usr/local/share/glib-2.0/schemas
    fi
    ;;
    POST-INSTALL)
    # compile schemas
    glib-compile-schemas /usr/local/share/glib-2.0/schemas
    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/mate-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/mate-terminal 50
    fi
    
    ;;
esac

exit 0
