# $FreeBSD$

PORTNAME=	texttable
PORTVERSION=	0.8.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@ixsystems.com
COMMENT=	ASCII tables generator module

LICENSE=	LGPL

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
