# $FreeBSD$
  
PORTNAME=       openzfs
PKGNAMESUFFIX=	-kmod-debug

COMMENT=        OpenZFS kernel module for FreeBSD with Debugging

MASTERDIR=      ${.CURDIR}/../../sysutils/openzfs-kmod

OPTIONS_DEFAULT=DEBUG
KMODTARGET=	openzfs-debug.ko

.include "${MASTERDIR}/Makefile"
