# $FreeBSD$

PORTNAME=	Flask-Bootstrap
PORTVERSION=	3.3.2.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@ixsystems.com
COMMENT=	Bootstrap packages for Flask

LICENSE=	BSD

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}flask:${PORTSDIR}/www/py-flask

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
