# $FreeBSD$

PORTNAME=	sh
PORTVERSION=	1.09
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@ixsystems.com
COMMENT=	Wrapper for launching shell commands in Python

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
