# $FreeBSD$
#

    COMMENT = Operating System Ports

    SUBDIR += buildkernel
    SUBDIR += buildworld
    SUBDIR += docs
    SUBDIR += kernel
    SUBDIR += kernel-debug
    SUBDIR += src
    SUBDIR += userland
    SUBDIR += userland-debug
    SUBDIR += userland-lib32
    SUBDIR += userland-tests

.include <bsd.port.subdir.mk>
