# $FreeBSD$

PORTNAME=	backports.shutil_get_terminal_size
PORTVERSION=	1.0.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@ixsystems.com
COMMENT=	A backport of the get_terminal_size function from Python 3.3's shutil.

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
