#!/bin/sh

case "$2" in
    POST-INSTALL)
    if [ -f /usr/local/etc/slim.conf ] ; then
        sed -i '' -e "s/current_theme       default/current_theme       ghostbsd/g" \
            /usr/local/etc/slim.conf
    fi
    ;;
esac

exit 0

