#!/bin/sh

case "$2" in
  POST-INSTALL)
    if [ -f /usr/local/etc/slim.conf ] ; then
      cat /usr/local/etc/slim.conf | grep -q 'current_theme       default'
      if [ "$?" -eq 0 ] ; then
        sed -i '' -e "s/current_theme       default/current_theme       forest/g" \
          /usr/local/etc/slim.conf
      fi
      cat /usr/local/etc/slim.conf | grep -q 'current_theme       ghostbsd'
      if [ "$?" -eq 0 ] ; then
        sed -i '' -e "s/current_theme       ghostbsd/current_theme       forest/g" \
          /usr/local/etc/slim.conf
      fi
    fi
    ;;
esac

exit 0

