# $FreeBSD$

PORTNAME=	docker-py
PORTVERSION=	1.7.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jceel@FreeBSD.org
COMMENT=	Python client for Docker.

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
