WITH_DEBUG=yes
PLIST=${.CURDIR}/../../lang/python39/pkg-plist
DISTINFO_FILE=${.CURDIR}/../../lang/python39/distinfo

.include "${.CURDIR}/../../lang/python39/Makefile"

PKGNAMESUFFIX:=${PYTHON_SUFFIX}-debugging
