COMMENT=        Python programming language (development version)
MASTERDIR=      ${.CURDIR}/../../lang/python39
PATCHDIR=       ${MASTERDIR}/files
PLIST=          ${MASTERDIR}/pkg-plist
DISTINFO_FILE=  ${MASTERDIR}/distinfo
WITH_DEBUG=     yes

.include "${MASTERDIR}/Makefile"

PKGNAMESUFFIX:= ${PYTHON_SUFFIX}-debugging
