# $FreeBSD$

PORTNAME=	sentry-sdk
PORTVERSION=	0.10.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	vladimirv@ixsystems.com
COMMENT=	Sentry-Python is an SDK for Sentry

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
