# $FreeBSD$

PORTNAME=	fusepy
DISTVERSION=	2.0.2
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
MASTER_SITES=	CHEESESHOP

MAINTAINER=	dev@ixsystems.com
COMMENT=	FUSE Python bindings

USES=		fuse pkgconfig iconv
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
