# $FreeBSD$

PORTNAME=	kernel-kmod-sentinel
PORTVERSION=	${BASEPKG_PORTVERSION}
CATEGORIES=	os
PKGNAMEPREFIX=	${OS_PKGNAMEPREFIX}

MAINTAINER=	kmoore@FreeBSD.org
COMMENT=	Metaport for ports kmod to ensure updates with kernel

USES=	metaport

.include "../Makefile.common"
.include <bsd.port.mk>
