#!/bin/sh

if [ -z "${PKG_ROOTDIR}" ] ; then
	PKG_ROOTDIR=/
fi

if [ "$2" != "POST-INSTALL" ] ; then
   exit 0
fi

cap_mkdb -l ${PKG_ROOTDIR}/etc/login.conf
pwd_mkdb -i -p -d  ${PKG_ROOTDIR}/etc ${PKG_ROOTDIR}/etc/master.passwd
services_mkdb -l -q -o ${PKG_ROOTDIR}/var/db/services.db ${PKG_ROOTDIR}/etc/services
chmod 1777 ${PKG_ROOTDIR}/tmp

sh ${PKG_ROOTDIR}/etc/pkgbase.setup $PKG_ROOTDIR
