# $FreeBSD$

PORTNAME=	pyte
PORTVERSION=	0.4.10
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@freenas.org
COMMENT=	Simple VTXXX-compatible terminal emulator.

NO_ARCH=	yes
USE_PYTHON=	autoplist concurrent distutils
USES=		python

.include <bsd.port.mk>
