# $FreeBSD$

PORTNAME=	qmlryver
PORTVERSION=	1.0
CATEGORIES=	net-im

MAINTAINER=	jt@ixsystems.com
COMMENT=	QML wraper for Ryver

LICENSE=	MIT

MAKE_JOBS_UNSAFE=yes

USES=		qmake qt:5
USE_QT=		core gui widgets network webengine svg multimedia buildtools
USE_GITHUB=	yes
GH_ACCOUNT=	q5sys
GH_PROJECT=	qmlryver
GH_TAGNAME=	91124b53116987dc99baacf3b5d455b0f6c051fd

.include <bsd.port.mk>
