WITH_DEBUG=yes
PLIST=${.CURDIR}/../../lang/python38/pkg-plist
DISTINFO_FILE=${.CURDIR}/../../lang/python38/distinfo

.include "${.CURDIR}/../../lang/python38/Makefile"

PKGNAMESUFFIX:=${PYTHON_SUFFIX}-debugging
